// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockery

import (
	"context"

	"github.com/ideagate/aigateway-core/gen/aigateway/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

type Usecase_Expecter struct {
	mock *mock.Mock
}

func (_m *Usecase) EXPECT() *Usecase_Expecter {
	return &Usecase_Expecter{mock: &_m.Mock}
}

// GetJobResults provides a mock function for the type Usecase
func (_mock *Usecase) GetJobResults(context1 context.Context, getJobResultsRequest *aigatewayv1.GetJobResultsRequest) ([]*aigatewayv1.GetJobResultsResponse, error) {
	ret := _mock.Called(context1, getJobResultsRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetJobResults")
	}

	var r0 []*aigatewayv1.GetJobResultsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *aigatewayv1.GetJobResultsRequest) ([]*aigatewayv1.GetJobResultsResponse, error)); ok {
		return returnFunc(context1, getJobResultsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *aigatewayv1.GetJobResultsRequest) []*aigatewayv1.GetJobResultsResponse); ok {
		r0 = returnFunc(context1, getJobResultsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*aigatewayv1.GetJobResultsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *aigatewayv1.GetJobResultsRequest) error); ok {
		r1 = returnFunc(context1, getJobResultsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Usecase_GetJobResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobResults'
type Usecase_GetJobResults_Call struct {
	*mock.Call
}

// GetJobResults is a helper method to define mock.On call
//   - context1 context.Context
//   - getJobResultsRequest *aigatewayv1.GetJobResultsRequest
func (_e *Usecase_Expecter) GetJobResults(context1 interface{}, getJobResultsRequest interface{}) *Usecase_GetJobResults_Call {
	return &Usecase_GetJobResults_Call{Call: _e.mock.On("GetJobResults", context1, getJobResultsRequest)}
}

func (_c *Usecase_GetJobResults_Call) Run(run func(context1 context.Context, getJobResultsRequest *aigatewayv1.GetJobResultsRequest)) *Usecase_GetJobResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *aigatewayv1.GetJobResultsRequest
		if args[1] != nil {
			arg1 = args[1].(*aigatewayv1.GetJobResultsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Usecase_GetJobResults_Call) Return(getJobResultsResponses []*aigatewayv1.GetJobResultsResponse, err error) *Usecase_GetJobResults_Call {
	_c.Call.Return(getJobResultsResponses, err)
	return _c
}

func (_c *Usecase_GetJobResults_Call) RunAndReturn(run func(context1 context.Context, getJobResultsRequest *aigatewayv1.GetJobResultsRequest) ([]*aigatewayv1.GetJobResultsResponse, error)) *Usecase_GetJobResults_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobStatus provides a mock function for the type Usecase
func (_mock *Usecase) GetJobStatus(context1 context.Context, getJobStatusRequest *aigatewayv1.GetJobStatusRequest) (*aigatewayv1.GetJobStatusResponse, error) {
	ret := _mock.Called(context1, getJobStatusRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetJobStatus")
	}

	var r0 *aigatewayv1.GetJobStatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *aigatewayv1.GetJobStatusRequest) (*aigatewayv1.GetJobStatusResponse, error)); ok {
		return returnFunc(context1, getJobStatusRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *aigatewayv1.GetJobStatusRequest) *aigatewayv1.GetJobStatusResponse); ok {
		r0 = returnFunc(context1, getJobStatusRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aigatewayv1.GetJobStatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *aigatewayv1.GetJobStatusRequest) error); ok {
		r1 = returnFunc(context1, getJobStatusRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Usecase_GetJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobStatus'
type Usecase_GetJobStatus_Call struct {
	*mock.Call
}

// GetJobStatus is a helper method to define mock.On call
//   - context1 context.Context
//   - getJobStatusRequest *aigatewayv1.GetJobStatusRequest
func (_e *Usecase_Expecter) GetJobStatus(context1 interface{}, getJobStatusRequest interface{}) *Usecase_GetJobStatus_Call {
	return &Usecase_GetJobStatus_Call{Call: _e.mock.On("GetJobStatus", context1, getJobStatusRequest)}
}

func (_c *Usecase_GetJobStatus_Call) Run(run func(context1 context.Context, getJobStatusRequest *aigatewayv1.GetJobStatusRequest)) *Usecase_GetJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *aigatewayv1.GetJobStatusRequest
		if args[1] != nil {
			arg1 = args[1].(*aigatewayv1.GetJobStatusRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Usecase_GetJobStatus_Call) Return(getJobStatusResponse *aigatewayv1.GetJobStatusResponse, err error) *Usecase_GetJobStatus_Call {
	_c.Call.Return(getJobStatusResponse, err)
	return _c
}

func (_c *Usecase_GetJobStatus_Call) RunAndReturn(run func(context1 context.Context, getJobStatusRequest *aigatewayv1.GetJobStatusRequest) (*aigatewayv1.GetJobStatusResponse, error)) *Usecase_GetJobStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitBulkChatCompletions provides a mock function for the type Usecase
func (_mock *Usecase) SubmitBulkChatCompletions(context1 context.Context, submitBulkChatCompletionsRequests []*aigatewayv1.SubmitBulkChatCompletionsRequest) (*aigatewayv1.SubmitBulkChatCompletionsResponse, error) {
	ret := _mock.Called(context1, submitBulkChatCompletionsRequests)

	if len(ret) == 0 {
		panic("no return value specified for SubmitBulkChatCompletions")
	}

	var r0 *aigatewayv1.SubmitBulkChatCompletionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*aigatewayv1.SubmitBulkChatCompletionsRequest) (*aigatewayv1.SubmitBulkChatCompletionsResponse, error)); ok {
		return returnFunc(context1, submitBulkChatCompletionsRequests)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*aigatewayv1.SubmitBulkChatCompletionsRequest) *aigatewayv1.SubmitBulkChatCompletionsResponse); ok {
		r0 = returnFunc(context1, submitBulkChatCompletionsRequests)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aigatewayv1.SubmitBulkChatCompletionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []*aigatewayv1.SubmitBulkChatCompletionsRequest) error); ok {
		r1 = returnFunc(context1, submitBulkChatCompletionsRequests)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Usecase_SubmitBulkChatCompletions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitBulkChatCompletions'
type Usecase_SubmitBulkChatCompletions_Call struct {
	*mock.Call
}

// SubmitBulkChatCompletions is a helper method to define mock.On call
//   - context1 context.Context
//   - submitBulkChatCompletionsRequests []*aigatewayv1.SubmitBulkChatCompletionsRequest
func (_e *Usecase_Expecter) SubmitBulkChatCompletions(context1 interface{}, submitBulkChatCompletionsRequests interface{}) *Usecase_SubmitBulkChatCompletions_Call {
	return &Usecase_SubmitBulkChatCompletions_Call{Call: _e.mock.On("SubmitBulkChatCompletions", context1, submitBulkChatCompletionsRequests)}
}

func (_c *Usecase_SubmitBulkChatCompletions_Call) Run(run func(context1 context.Context, submitBulkChatCompletionsRequests []*aigatewayv1.SubmitBulkChatCompletionsRequest)) *Usecase_SubmitBulkChatCompletions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*aigatewayv1.SubmitBulkChatCompletionsRequest
		if args[1] != nil {
			arg1 = args[1].([]*aigatewayv1.SubmitBulkChatCompletionsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Usecase_SubmitBulkChatCompletions_Call) Return(submitBulkChatCompletionsResponse *aigatewayv1.SubmitBulkChatCompletionsResponse, err error) *Usecase_SubmitBulkChatCompletions_Call {
	_c.Call.Return(submitBulkChatCompletionsResponse, err)
	return _c
}

func (_c *Usecase_SubmitBulkChatCompletions_Call) RunAndReturn(run func(context1 context.Context, submitBulkChatCompletionsRequests []*aigatewayv1.SubmitBulkChatCompletionsRequest) (*aigatewayv1.SubmitBulkChatCompletionsResponse, error)) *Usecase_SubmitBulkChatCompletions_Call {
	_c.Call.Return(run)
	return _c
}

// SyncBatchJobStatus provides a mock function for the type Usecase
func (_mock *Usecase) SyncBatchJobStatus(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for SyncBatchJobStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Usecase_SyncBatchJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncBatchJobStatus'
type Usecase_SyncBatchJobStatus_Call struct {
	*mock.Call
}

// SyncBatchJobStatus is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Usecase_Expecter) SyncBatchJobStatus(context1 interface{}) *Usecase_SyncBatchJobStatus_Call {
	return &Usecase_SyncBatchJobStatus_Call{Call: _e.mock.On("SyncBatchJobStatus", context1)}
}

func (_c *Usecase_SyncBatchJobStatus_Call) Run(run func(context1 context.Context)) *Usecase_SyncBatchJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Usecase_SyncBatchJobStatus_Call) Return(err error) *Usecase_SyncBatchJobStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Usecase_SyncBatchJobStatus_Call) RunAndReturn(run func(context1 context.Context) error) *Usecase_SyncBatchJobStatus_Call {
	_c.Call.Return(run)
	return _c
}
