// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockery

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewDistributionLock creates a new instance of DistributionLock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDistributionLock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DistributionLock {
	mock := &DistributionLock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DistributionLock is an autogenerated mock type for the DistributionLock type
type DistributionLock struct {
	mock.Mock
}

type DistributionLock_Expecter struct {
	mock *mock.Mock
}

func (_m *DistributionLock) EXPECT() *DistributionLock_Expecter {
	return &DistributionLock_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function for the type DistributionLock
func (_mock *DistributionLock) Acquire(ctx context.Context, lockKey string, ttl time.Duration) (bool, error) {
	ret := _mock.Called(ctx, lockKey, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, lockKey, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) bool); ok {
		r0 = returnFunc(ctx, lockKey, ttl)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, lockKey, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DistributionLock_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type DistributionLock_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - ctx context.Context
//   - lockKey string
//   - ttl time.Duration
func (_e *DistributionLock_Expecter) Acquire(ctx interface{}, lockKey interface{}, ttl interface{}) *DistributionLock_Acquire_Call {
	return &DistributionLock_Acquire_Call{Call: _e.mock.On("Acquire", ctx, lockKey, ttl)}
}

func (_c *DistributionLock_Acquire_Call) Run(run func(ctx context.Context, lockKey string, ttl time.Duration)) *DistributionLock_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DistributionLock_Acquire_Call) Return(b bool, err error) *DistributionLock_Acquire_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *DistributionLock_Acquire_Call) RunAndReturn(run func(ctx context.Context, lockKey string, ttl time.Duration) (bool, error)) *DistributionLock_Acquire_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type DistributionLock
func (_mock *DistributionLock) Release(ctx context.Context, lockKey string) error {
	ret := _mock.Called(ctx, lockKey)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, lockKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DistributionLock_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type DistributionLock_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - lockKey string
func (_e *DistributionLock_Expecter) Release(ctx interface{}, lockKey interface{}) *DistributionLock_Release_Call {
	return &DistributionLock_Release_Call{Call: _e.mock.On("Release", ctx, lockKey)}
}

func (_c *DistributionLock_Release_Call) Run(run func(ctx context.Context, lockKey string)) *DistributionLock_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DistributionLock_Release_Call) Return(err error) *DistributionLock_Release_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DistributionLock_Release_Call) RunAndReturn(run func(ctx context.Context, lockKey string) error) *DistributionLock_Release_Call {
	_c.Call.Return(run)
	return _c
}
