// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockery

import (
	"context"

	"github.com/ideagate/aigateway-core/internal/aigateway/models"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateBatchJob provides a mock function for the type Repository
func (_mock *Repository) CreateBatchJob(ctx context.Context, job *models.BatchJob) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatchJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.BatchJob) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_CreateBatchJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatchJob'
type Repository_CreateBatchJob_Call struct {
	*mock.Call
}

// CreateBatchJob is a helper method to define mock.On call
//   - ctx context.Context
//   - job *models.BatchJob
func (_e *Repository_Expecter) CreateBatchJob(ctx interface{}, job interface{}) *Repository_CreateBatchJob_Call {
	return &Repository_CreateBatchJob_Call{Call: _e.mock.On("CreateBatchJob", ctx, job)}
}

func (_c *Repository_CreateBatchJob_Call) Run(run func(ctx context.Context, job *models.BatchJob)) *Repository_CreateBatchJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.BatchJob
		if args[1] != nil {
			arg1 = args[1].(*models.BatchJob)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_CreateBatchJob_Call) Return(err error) *Repository_CreateBatchJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_CreateBatchJob_Call) RunAndReturn(run func(ctx context.Context, job *models.BatchJob) error) *Repository_CreateBatchJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveBatchJobs provides a mock function for the type Repository
func (_mock *Repository) GetActiveBatchJobs(ctx context.Context) ([]*models.BatchJob, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveBatchJobs")
	}

	var r0 []*models.BatchJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*models.BatchJob, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*models.BatchJob); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.BatchJob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetActiveBatchJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveBatchJobs'
type Repository_GetActiveBatchJobs_Call struct {
	*mock.Call
}

// GetActiveBatchJobs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) GetActiveBatchJobs(ctx interface{}) *Repository_GetActiveBatchJobs_Call {
	return &Repository_GetActiveBatchJobs_Call{Call: _e.mock.On("GetActiveBatchJobs", ctx)}
}

func (_c *Repository_GetActiveBatchJobs_Call) Run(run func(ctx context.Context)) *Repository_GetActiveBatchJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_GetActiveBatchJobs_Call) Return(batchJobs []*models.BatchJob, err error) *Repository_GetActiveBatchJobs_Call {
	_c.Call.Return(batchJobs, err)
	return _c
}

func (_c *Repository_GetActiveBatchJobs_Call) RunAndReturn(run func(ctx context.Context) ([]*models.BatchJob, error)) *Repository_GetActiveBatchJobs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBatchJob provides a mock function for the type Repository
func (_mock *Repository) UpdateBatchJob(ctx context.Context, job *models.BatchJob) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatchJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.BatchJob) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_UpdateBatchJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBatchJob'
type Repository_UpdateBatchJob_Call struct {
	*mock.Call
}

// UpdateBatchJob is a helper method to define mock.On call
//   - ctx context.Context
//   - job *models.BatchJob
func (_e *Repository_Expecter) UpdateBatchJob(ctx interface{}, job interface{}) *Repository_UpdateBatchJob_Call {
	return &Repository_UpdateBatchJob_Call{Call: _e.mock.On("UpdateBatchJob", ctx, job)}
}

func (_c *Repository_UpdateBatchJob_Call) Run(run func(ctx context.Context, job *models.BatchJob)) *Repository_UpdateBatchJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.BatchJob
		if args[1] != nil {
			arg1 = args[1].(*models.BatchJob)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_UpdateBatchJob_Call) Return(err error) *Repository_UpdateBatchJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_UpdateBatchJob_Call) RunAndReturn(run func(ctx context.Context, job *models.BatchJob) error) *Repository_UpdateBatchJob_Call {
	_c.Call.Return(run)
	return _c
}
