// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockery

import (
	"context"

	"github.com/ideagate/aigateway-core/gen/aigateway/v1"
	"github.com/ideagate/aigateway-core/internal/aigateway/providers"
	"github.com/ideagate/aigateway-core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

type Provider_Expecter struct {
	mock *mock.Mock
}

func (_m *Provider) EXPECT() *Provider_Expecter {
	return &Provider_Expecter{mock: &_m.Mock}
}

// ChatCompletion provides a mock function for the type Provider
func (_mock *Provider) ChatCompletion(ctx context.Context, request *models.ChatCompletionRequest) (*models.ChatCompletionResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ChatCompletion")
	}

	var r0 *models.ChatCompletionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.ChatCompletionRequest) (*models.ChatCompletionResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.ChatCompletionRequest) *models.ChatCompletionResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ChatCompletionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.ChatCompletionRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Provider_ChatCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatCompletion'
type Provider_ChatCompletion_Call struct {
	*mock.Call
}

// ChatCompletion is a helper method to define mock.On call
//   - ctx context.Context
//   - request *models.ChatCompletionRequest
func (_e *Provider_Expecter) ChatCompletion(ctx interface{}, request interface{}) *Provider_ChatCompletion_Call {
	return &Provider_ChatCompletion_Call{Call: _e.mock.On("ChatCompletion", ctx, request)}
}

func (_c *Provider_ChatCompletion_Call) Run(run func(ctx context.Context, request *models.ChatCompletionRequest)) *Provider_ChatCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.ChatCompletionRequest
		if args[1] != nil {
			arg1 = args[1].(*models.ChatCompletionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Provider_ChatCompletion_Call) Return(chatCompletionResponse *models.ChatCompletionResponse, err error) *Provider_ChatCompletion_Call {
	_c.Call.Return(chatCompletionResponse, err)
	return _c
}

func (_c *Provider_ChatCompletion_Call) RunAndReturn(run func(ctx context.Context, request *models.ChatCompletionRequest) (*models.ChatCompletionResponse, error)) *Provider_ChatCompletion_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatchJobStatus provides a mock function for the type Provider
func (_mock *Provider) GetBatchJobStatus(ctx context.Context, referenceID string) (*providers.BatchJobStatusResult, error) {
	ret := _mock.Called(ctx, referenceID)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchJobStatus")
	}

	var r0 *providers.BatchJobStatusResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*providers.BatchJobStatusResult, error)); ok {
		return returnFunc(ctx, referenceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *providers.BatchJobStatusResult); ok {
		r0 = returnFunc(ctx, referenceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.BatchJobStatusResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, referenceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Provider_GetBatchJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatchJobStatus'
type Provider_GetBatchJobStatus_Call struct {
	*mock.Call
}

// GetBatchJobStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - referenceID string
func (_e *Provider_Expecter) GetBatchJobStatus(ctx interface{}, referenceID interface{}) *Provider_GetBatchJobStatus_Call {
	return &Provider_GetBatchJobStatus_Call{Call: _e.mock.On("GetBatchJobStatus", ctx, referenceID)}
}

func (_c *Provider_GetBatchJobStatus_Call) Run(run func(ctx context.Context, referenceID string)) *Provider_GetBatchJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Provider_GetBatchJobStatus_Call) Return(batchJobStatusResult *providers.BatchJobStatusResult, err error) *Provider_GetBatchJobStatus_Call {
	_c.Call.Return(batchJobStatusResult, err)
	return _c
}

func (_c *Provider_GetBatchJobStatus_Call) RunAndReturn(run func(ctx context.Context, referenceID string) (*providers.BatchJobStatusResult, error)) *Provider_GetBatchJobStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type Provider
func (_mock *Provider) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Provider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Provider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Provider_Expecter) Name() *Provider_Name_Call {
	return &Provider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Provider_Name_Call) Run(run func()) *Provider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Provider_Name_Call) Return(s string) *Provider_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Provider_Name_Call) RunAndReturn(run func() string) *Provider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitBatchJob provides a mock function for the type Provider
func (_mock *Provider) SubmitBatchJob(ctx context.Context, request []*aigatewayv1.SubmitBulkChatCompletionsRequest) (*aigatewayv1.SubmitBulkChatCompletionsResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SubmitBatchJob")
	}

	var r0 *aigatewayv1.SubmitBulkChatCompletionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*aigatewayv1.SubmitBulkChatCompletionsRequest) (*aigatewayv1.SubmitBulkChatCompletionsResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*aigatewayv1.SubmitBulkChatCompletionsRequest) *aigatewayv1.SubmitBulkChatCompletionsResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aigatewayv1.SubmitBulkChatCompletionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []*aigatewayv1.SubmitBulkChatCompletionsRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Provider_SubmitBatchJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitBatchJob'
type Provider_SubmitBatchJob_Call struct {
	*mock.Call
}

// SubmitBatchJob is a helper method to define mock.On call
//   - ctx context.Context
//   - request []*aigatewayv1.SubmitBulkChatCompletionsRequest
func (_e *Provider_Expecter) SubmitBatchJob(ctx interface{}, request interface{}) *Provider_SubmitBatchJob_Call {
	return &Provider_SubmitBatchJob_Call{Call: _e.mock.On("SubmitBatchJob", ctx, request)}
}

func (_c *Provider_SubmitBatchJob_Call) Run(run func(ctx context.Context, request []*aigatewayv1.SubmitBulkChatCompletionsRequest)) *Provider_SubmitBatchJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*aigatewayv1.SubmitBulkChatCompletionsRequest
		if args[1] != nil {
			arg1 = args[1].([]*aigatewayv1.SubmitBulkChatCompletionsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Provider_SubmitBatchJob_Call) Return(submitBulkChatCompletionsResponse *aigatewayv1.SubmitBulkChatCompletionsResponse, err error) *Provider_SubmitBatchJob_Call {
	_c.Call.Return(submitBulkChatCompletionsResponse, err)
	return _c
}

func (_c *Provider_SubmitBatchJob_Call) RunAndReturn(run func(ctx context.Context, request []*aigatewayv1.SubmitBulkChatCompletionsRequest) (*aigatewayv1.SubmitBulkChatCompletionsResponse, error)) *Provider_SubmitBatchJob_Call {
	_c.Call.Return(run)
	return _c
}
