name: CI

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    name: Lint, Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

      - name: Run unit tests
        run: make test
