package usecase

import (
	"bytes"
	"context"
	"encoding/binary"
	"fmt"
	"time"

	aigatewayv1 "github.com/ideagate/aigateway-core/gen/aigateway/v1"
	"github.com/ideagate/aigateway-core/internal/aigateway/models"
	"github.com/ideagate/aigateway-core/internal/aigateway/providers"
	"github.com/ideagate/aigateway-core/internal/aigateway/repository"
	"google.golang.org/protobuf/proto"
)

type Usecase interface {
	SubmitBulkChatCompletions(context.Context, []*aigatewayv1.SubmitBulkChatCompletionsRequest) (*aigatewayv1.SubmitBulkChatCompletionsResponse, error)
	GetJobStatus(context.Context, *aigatewayv1.GetJobStatusRequest) (*aigatewayv1.GetJobStatusResponse, error)
	GetJobResults(context.Context, *aigatewayv1.GetJobResultsRequest) ([]*aigatewayv1.GetJobResultsResponse, error)
}

type usecase struct {
	provider   providers.Provider
	repository repository.Repository
}

// New constructs the concrete Usecase implementation.
func New(provider providers.Provider, repo repository.Repository) Usecase {
	return &usecase{
		provider:   provider,
		repository: repo,
	}
}

// SubmitBulkChatCompletions submits a batch job via the provider, then persists
// a pending BatchJob row in the database.
func (u *usecase) SubmitBulkChatCompletions(ctx context.Context, requests []*aigatewayv1.SubmitBulkChatCompletionsRequest) (*aigatewayv1.SubmitBulkChatCompletionsResponse, error) {
	// Serialize requests to proto binary bytes for storage.
	requestProto, err := marshalRequests(requests)
	if err != nil {
		return nil, fmt.Errorf("failed to serialize requests: %w", err)
	}

	// Call the provider to submit the batch job.
	resp, err := u.provider.SubmitBatchJob(ctx, requests)
	if err != nil {
		return nil, fmt.Errorf("failed to submit batch job: %w", err)
	}

	// Persist a pending row in batch_jobs.
	// ID is auto-generated by the BatchJob.BeforeCreate GORM hook.
	now := time.Now()
	referenceID := resp.GetJobId()
	batchJob := &models.BatchJob{
		RequestProto:       requestProto,
		LengthData:         len(requests),
		Status:             models.BatchJobStatusPending,
		ReferenceID:        &referenceID,
		Provider:           u.provider.Name(),
		CreatedTimestamp:   now,
		SubmittedTimestamp: &now,
	}

	if err := u.repository.CreateBatchJob(ctx, batchJob); err != nil {
		return nil, fmt.Errorf("failed to persist batch job: %w", err)
	}

	return resp, nil
}

func (u *usecase) GetJobStatus(ctx context.Context, req *aigatewayv1.GetJobStatusRequest) (*aigatewayv1.GetJobStatusResponse, error) {
	panic("not implemented")
}

func (u *usecase) GetJobResults(ctx context.Context, req *aigatewayv1.GetJobResultsRequest) ([]*aigatewayv1.GetJobResultsResponse, error) {
	panic("not implemented")
}

// marshalRequests encodes a slice of requests into a length-delimited proto
// binary blob. Each entry is written as [4-byte big-endian length][proto bytes].
func marshalRequests(requests []*aigatewayv1.SubmitBulkChatCompletionsRequest) ([]byte, error) {
	var buf bytes.Buffer
	for i, r := range requests {
		b, err := proto.Marshal(r)
		if err != nil {
			return nil, fmt.Errorf("request %d: %w", i, err)
		}
		if err := binary.Write(&buf, binary.BigEndian, uint32(len(b))); err != nil {
			return nil, fmt.Errorf("request %d: writing length: %w", i, err)
		}
		buf.Write(b)
	}
	return buf.Bytes(), nil
}
